# Generated by Django 5.2.14 on 2026-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar')], max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('time_info', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('quota', models.IntegerField(default=100)),
                ('registered', models.IntegerField(default=0)),
                ('sdg_tags', models.JSONField(default=list)),
                ('emoji', models.CharField(default='🌿', max_length=10)),
                ('cover_color', models.CharField(default='linear-gradient(135deg,#ABC270,#5A7A20)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
