# Generated by Django 5.2.14 on 2026-05-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='emoji',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_color',
            field=models.CharField(default='linear-gradient(135deg,#74C69D,#2D6A4F)', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='sdg_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
